### ISSUE TITLE
attempting to download the wrong key

### ISSUE THREAD

**Issue by pmiess** [0install/feedlint#2]
I sign feeds with a signing subkey like this

> 0publish -x -k16AD1160 cloc.xml

When I run feedlint it attempts to download the wrong key

> Checking https://gitlab.com/pmiess/0install-feeds/raw/test/public/cloc.xml                                                 [ Fetched ]
>   Checking key https://gitlab.com/pmiess/0install-feeds/raw/test/public/3BAF7E247418A850.gpg                               [ ERROR ]
>   HTTP Error 404: Not Found
> 
> ERRORS FOUND: 1
 
it should be downloading 6ABB34B516AD1160.gpg

**Comment by talex5** [comment]
Seems to be some confusion between primary keys and subkeys. I've pushed a possible fix in https://github.com/0install/feedlint/commit/ec442ad02183e265bab1449522529672b356bf13. Please reopen if it doesn't work!

**Comment by pmiess** [comment]
I cloned the repo and ran it locally, it works for me.
Thanks
